# Generated by Django 3.0.3 on 2020-03-02 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CveInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(help_text='Enter the cve_id', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneScore', models.FloatField(help_text='This is the general risk score of the product', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventorName', models.CharField(max_length=200)),
                ('ventorLink', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cve_ids', models.ManyToManyField(help_text='Select the cve_id for this cve_id', to='datamanage.CveInfo')),
                ('risk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamanage.Risk')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamanage.Vendor')),
            ],
        ),
    ]
