# Generated by Django 3.0.3 on 2020-03-02 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamanage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='ventorLink',
            new_name='vendorLink',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='ventorName',
            new_name='vendorName',
        ),
    ]
